services:
  fs-auth-app:
    container_name: fs-auth-app
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - ./:/app
      - .logs/:/app/.logs
    working_dir: /app
    networks:
      - fs-auth-backend
    tty: true
    stdin_open: true
    depends_on:
      - fs-auth-postgres

  fs-auth-postgres:
    container_name: fs-auth-postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    networks:
      - fs-auth-backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  fs-auth-pgadmin:
    container_name: fs-auth-pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "5500:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-storage:/var/lib/pgadmin
    depends_on:
      - fs-auth-postgres
    networks:
      - fs-auth-backend
    restart: unless-stopped

volumes:
  postgres-storage:
  pgadmin-storage:

networks:
  fs-auth-backend:
    driver: bridge
